version: '3.8'

services:
  web:
    build: .
    container_name: library_web

    env_file:
      - .env

    entrypoint: ["./entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: library_db

    env_file:
      - .env

    ports:
      - "5432:5432"